import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Numeric, DateTime, ForeignKey, Text, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Recommendation(Base):
    """Task redistribution and workload recommendations generated by the engine."""
    __tablename__ = "recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    type = Column(String(50), nullable=False)  # task_reassignment, workload_alert, project_risk_alert
    source_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    target_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    task_id = Column(UUID(as_uuid=True), ForeignKey("tasks.id"), nullable=True, index=True)
    projected_source_util = Column(Numeric(5, 2))
    projected_target_util = Column(Numeric(5, 2))
    impact_score = Column(Numeric(5, 2))
    confidence_score = Column(Numeric(5, 2))
    status = Column(String(20), default="pending", index=True)  # pending, approved, rejected, deferred, applied
    rationale = Column(Text)
    reviewed_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    # Relationships
    source_user = relationship("User", back_populates="source_recommendations",
                               foreign_keys=[source_user_id])
    target_user = relationship("User", back_populates="target_recommendations",
                               foreign_keys=[target_user_id])
    task = relationship("Task", back_populates="recommendations")
    reviewer = relationship("User", back_populates="reviewed_recommendations",
                            foreign_keys=[reviewed_by])

    __table_args__ = (
        Index("ix_recommendations_status_created", "status", "created_at"),
        Index("ix_recommendations_type", "type"),
    )

    def __repr__(self):
        return f"<Recommendation id={self.id} type={self.type} status={self.status}>"


class AuditLog(Base):
    """Immutable audit trail for all recommendation actions and task reassignments."""
    __tablename__ = "audit_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    action = Column(String(100), nullable=False)  # recommendation_approved, recommendation_rejected, task_reassigned
    actor_id = Column(UUID(as_uuid=True), ForeignKey("platform_users.id"), nullable=False)
    entity_type = Column(String(50))  # recommendation, task
    entity_id = Column(UUID(as_uuid=True))
    metadata = Column(Text)  # JSON blob with before/after state
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    __table_args__ = (
        Index("ix_audit_actor_created", "actor_id", "created_at"),
        Index("ix_audit_entity", "entity_type", "entity_id"),
    )
